language: cpp
sudo: required

services:
    - docker
    
before_install:
 - docker run -d --name ubuntu-test -v $(pwd):/travis ubuntu:latest tail -f /dev/null
 - docker ps

install:
 - docker exec -t ubuntu-test bash -c "apt-get update;
   apt-get install -y git;
   apt-get install -y qtcreator qtbase5-dev qt5-default;
   apt-get install -y libxxf86vm-dev libxcursor-dev libxrandr-dev libxi-dev libxinerama-dev libudev-dev;
   apt-get install -y libavcodec-dev libavformat-dev libswscale-dev;
   apt-get install -y g++;
   apt-get install -y libdc1394-22"
 
script:
 - docker exec -t ubuntu-test bash -c "cd /travis;
   ls -la;
   qmake -recursive && make"

branches:
  only:
    - master
    - develop
    
notifications:
    email:
        recipients:
          - marcus.hudritsch@bfh.ch
        on_success: never
        on_failure: always